export const COLOR_MAP = {
    red: { name: 'Red', value: '#ff0000' },
    blue: { name: 'Blue', value: '#0000ff' },
    green: { name: 'Green', value: '#00ff00' },
    yellow: { name: 'Yellow', value: '#ffff00' },
    purple: { name: 'Purple', value: '#800080' },
    orange: { name: 'Orange', value: '#ffa500' },
    pink: { name: 'Pink', value: '#ffc0cb' },
    cyan: { name: 'Cyan', value: '#00ffff' },
    lime: { name: 'Lime', value: '#32cd32' },
};

export const LEVELS = [
    {
        level: 0,
    },
    {
        level: 1,
        gridSize: 3,
        availableColors: ['red', 'blue', 'green'],
        targetColors: ['red'],
        timeSeconds: 15,
    },
    {
        level: 2,
        gridSize: 4,
        availableColors: ['red', 'blue', 'green', 'yellow'],
        targetColors: ['red', 'blue'],
        timeSeconds: 20,
    },
    {
        level: 3,
        gridSize: 5,
        availableColors: ['red', 'blue', 'green', 'yellow'],
        targetColors: ['red', 'blue', 'yellow'],
        timeSeconds: 30,
    },
    {
        level: 4,
        gridSize: 5,
        availableColors: ['red', 'blue', 'green', 'yellow', 'purple'],
        targetColors: ['blue', 'yellow', 'purple'],
        timeSeconds: 35,
    },
    {
        level: 5,
        gridSize: 6,
        availableColors: ['red', 'blue', 'green', 'yellow', 'purple'],
        targetColors: ['green', 'yellow', 'purple'],
        timeSeconds: 40,
    },
    {
        level: 6,
        gridSize: 6,
        availableColors: ['red', 'blue', 'green', 'yellow', 'purple', 'orange'],
        targetColors: ['green', 'yellow', 'purple', 'orange'],
        timeSeconds: 45,
    },
    {
        level: 7,
        gridSize: 7,
        availableColors: ['red', 'blue', 'green', 'yellow', 'purple', 'orange'],
        targetColors: ['yellow', 'purple', 'orange', 'blue'],
        timeSeconds: 50,
    },
    {
        level: 8,
        gridSize: 7,
        availableColors: [
            'red',
            'blue',
            'green',
            'yellow',
            'purple',
            'orange',
            'pink',
        ],
        targetColors: ['green', 'yellow', 'purple', 'orange', 'pink'],
        timeSeconds: 60,
    },
    {
        level: 9,
        gridSize: 8,
        availableColors: [
            'red',
            'blue',
            'green',
            'yellow',
            'purple',
            'orange',
            'pink',
            'cyan',
        ],
        targetColors: ['blue', 'green', 'yellow', 'purple', 'orange', 'pink'],
        timeSeconds: 70,
    },
    {
        level: 10,
        gridSize: 8,
        availableColors: [
            'red',
            'blue',
            'green',
            'yellow',
            'purple',
            'orange',
            'pink',
            'cyan',
            'lime',
        ],
        targetColors: [
            'red',
            'blue',
            'green',
            'yellow',
            'purple',
            'orange',
            'pink',
        ],
        timeSeconds: 90,
    },
];
